[server]
enableCORS = false
enableXsrfProtection = false

[theme]
base = "light"
primaryColor = "#3670F2"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#31333F"
font = "sans serif"
